# Project: cpp-gpengine
# Makefile created by Pablo Garcia Gonzalez 
# Date: 11.11.2003

CPP  = g++ 
OBJ  = 	XML.o   
LIBS = -L"/usr/lib" -L"../../lib" ../../lib/cpp-gpengine-1.2.0.a  
CXXINCS = -I"../../include/" -I"/usr/include" 
BIN  = XML 
CXXFLAGS = $(CXXINCS)  

all: XML 

clean: 
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o "XML" $(LIBS)

XML.o: XML.cpp
	$(CPP) -c -Wall XML.cpp -o XML.o $(CXXFLAGS)


